name: ATP-OSM Sync

on:
    schedule:
        - cron: '0 0 * * 3' # Run every Wednesday at midnight
    workflow_dispatch: # Allow manual trigger

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24.x'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Install Osmium Tool
              run: |
                  sudo apt-get update
                  sudo apt-get install -y osmium-tool

            - name: Run synchronization script
              run: npm run sync

            - name: Build CSS
              run: npm run build:css

            - name: Upload dashboard
              uses: actions/upload-artifact@v7
              with:
                  name: atp-osm-dashboard
                  path: |
                      output/
