name: ATP-OSM Sync

on:
    workflow_dispatch:
        inputs:
            mock:
                description: 'Run with mock data'
                required: false
                default: false
                type: boolean

jobs:
    sync:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            issues: write

        env:
            NO_DEBUG: true

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24.x'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Install Osmium Tool
              if: github.event.inputs.mock != 'true' && env.MOCK != 'true'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y osmium-tool

            - name: Run synchronisation script
              run: npm run sync
              env:
                  MOCK: ${{ github.event.inputs.mock }}
                  IS_WEEKLY_RUN: ${{ github.event_name == 'schedule' }}

            - name: Build CSS
              run: npm run build:css

            - name: Upload dashboard
              uses: actions/upload-artifact@v7
              with:
                  name: atp-osm-dashboard
                  path: |
                      output/

            - name: Upload safe edits
              uses: actions/upload-artifact@v7
              with:
                  name: safe-edits
                  path: |
                      safe-edits/

            - name: Dummy Deployment
              if: github.ref == 'refs/heads/main'
              run: echo "Deploying to Cloudflare Pages... (Dummy Step)"

            - name: Run feedback bot
              if: github.event_name == 'schedule' && github.ref == 'refs/heads/main'
              run: node src/feedback_bot.js
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
